# Generated by Django 5.1.1 on 2024-09-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default='english', help_text='Language of the book', max_length=2),
        ),
    ]
