# Generated by Django 5.1.1 on 2024-09-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default='english', help_text='Language of the book', max_length=20),
        ),
    ]
